### ISSUE TITLE
Autonomous wait points

### ISSUE THREAD

**Issue by tcjinaz** [Pridetronics/Crescendo-V1#2]
It would be useful to have a couple of points in the auton patterns to wait for some time, programmable by drivers on the field.

The first would be at the very beginning so that the robot sits still for a few seconds. This can make room for another robot to operate "in front" of us without interference.

There will probably be at least one other point in a pattern that would logically be a place to drop in a similar delay.

If we only had LiDAR :)

**Comment by Matthew-PT** [comment]
Done
